version: '3'
services:  
  azdobuildagent:
    build: 
      context: ./
      dockerfile: Dockerfile   
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock 
      - /azdowork:/azdowork    
    env_file:
    - .env   
    #restart: always